import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <nav className="flex gap-6 p-4 bg-gray-900 text-white">
          <Link href="/" className="hover:text-gray-300 font-semibold">
            Home
          </Link>
          <Link href="/animals" className="hover:text-gray-300 font-semibold">
            Animals
          </Link>
          <Link
            href="/add-animal"
            className="hover:text-gray-300 font-semibold"
          >
            Add a new animal
          </Link>
        </nav>
        <main className="max-w-5xl mx-auto px-6 py-8">{children}</main>
      </body>
    </html>
  );
}
